apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: rnk-expense
spec:
  type: LoadBalancer
  selector: 
    app: frontend
    tier: web-jenkins
    project: expense
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetport }}